# Generated by Django 3.2.3 on 2021-05-20 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitterClone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='tweet',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='tweet_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
