# Generated by Django 3.2.3 on 2021-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterClone', '0002_auto_20210520_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='tweet',
            field=models.CharField(max_length=300, verbose_name=''),
        ),
    ]
