# Generated by Django 3.2 on 2021-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterClone', '0003_alter_tweetmodel_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='tweet',
            field=models.TextField(max_length=300, verbose_name=''),
        ),
    ]
